spring:
  datasource:
    url: S{JDBC_HOST:jdbc:mysql://localhost:3306/springhibernate?useSSL=false&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_ROOT_PASSWORD:password}
  jpa:
    database: MYSQL
    showSql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: false